"""Ingredient Table

Revision ID: 29fa2fd1f068
Revises: ecee08d332bc
Create Date: 2024-02-13 09:29:06.473605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fa2fd1f068'
down_revision = 'ecee08d332bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_burgers')),
    sa.UniqueConstraint('name', name=op.f('uq_burgers_name'))
    )
    op.drop_table('hamburgers')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingredients_hamburger_id_hamburgers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ingredients_hamburger_id_burgers'), 'burgers', ['hamburger_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ingredients_hamburger_id_burgers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ingredients_hamburger_id_hamburgers', 'hamburgers', ['hamburger_id'], ['id'])

    op.create_table('hamburgers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_hamburgers'),
    sa.UniqueConstraint('name', name='uq_hamburgers_name')
    )
    op.drop_table('burgers')
    # ### end Alembic commands ###
