"""empty message

Revision ID: 43981c6b4f17
Revises: a5d2bce3dffa
Create Date: 2024-02-12 13:51:54.114307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43981c6b4f17'
down_revision = 'a5d2bce3dffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hamburgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hamburgers')),
    sa.UniqueConstraint('name', name=op.f('uq_hamburgers_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hamburgers')
    # ### end Alembic commands ###
