"""create tables

Revision ID: ae1ccf587eea
Revises: 
Create Date: 2024-02-16 09:32:34.630736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1ccf587eea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_burgers')),
    sa.UniqueConstraint('name', name=op.f('uq_burgers_name'))
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hamburger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hamburger_id'], ['burgers.id'], name=op.f('fk_ingredients_hamburger_id_burgers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('burgers')
    # ### end Alembic commands ###
