"""Ingredient Table

Revision ID: ecee08d332bc
Revises: a0df7b6ae51e
Create Date: 2024-02-13 08:52:39.404822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecee08d332bc'
down_revision = 'a0df7b6ae51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hamburger_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ingredients_hamburger_id_hamburgers'), 'hamburgers', ['hamburger_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ingredients_hamburger_id_hamburgers'), type_='foreignkey')
        batch_op.drop_column('hamburger_id')

    # ### end Alembic commands ###
